{ image: gitpod/workspace-mongodb }

vscode:
  extensions:
    - eventyret.bootstrap-4-cdn-snippet@1.3.0:3EJTfpRZ7YoP6Ty3NIdt5Q==
vscode:
  extensions:
    - eventyret.bootstrap-4-cdn-snippet@1.3.0:3EJTfpRZ7YoP6Ty3NIdt5Q==
vscode:
  extensions:
    - usernamehw.errorlens@2.9.0:Ts3sG3L2E2VzHqJ5M0mX7w==
vscode:
  extensions:
    - usernamehw.errorlens@2.9.0:Ts3sG3L2E2VzHqJ5M0mX7w==